version: "3"

services:

  redis:

    image: redis:latest
    container_name: redis
    networks:
      - api-ipgeolocation-net
    restart: always

  ipgeolocation-api-cache:

    image: swathikarun/ipgeolocation-api-service:v1
    container_name: ipgeolocation-api-cache
    networks:
      - api-ipgeolocation-net
    ports:
      - "8080:8080"
    restart: always
    environment:
      - REDIS_HOST=redis
      - APP_PORT=8080
      - API_KEY_FROM_SECRETSMANAGER=True
      - SECRET_NAME=ipstack
      - SECRET_KEY=api_key
      - REGION_NAME=ap-south-1

  ipgeolocation-frontend:

    image: swathikarun/ipgeolocation-frontend:v1
    container_name: ipgeolocation-frontend
    networks:
      - api-ipgeolocation-net
    ports:
      - "80:8080"
    restart: always
    environment:
      - API_SERVER=ipgeolocation-api-cache
      - API_SERVER_PORT=8080
      - API_PATH=/api/v1/
      - APP_PORT=8080


networks:
  api-ipgeolocation-net:
